/** This file is the place to store all the deck lists */

// Okidogi Barbaracle deck
var okidogi = new DeckList("Okidogi Barbaracle",
    ["<strong>Pokémon: 19</strong>",
        "3 Okidogi TWM 111",
        "3 Solrock MEG 75",
        "2 Binacle POR 42",
        "2 Barbaracle POR 43",
        "2 Lunatone MEG 74",
        "1 Ethan's Sudowoodo DRI 93",
        "1 Bloodmoon Ursaluna PRE 54",
        "1 Shaymin DRI 10",
        "1 Psyduck ASC 39",
        "1 Moltres PFL 14",
        "1 Patrat CRI 70",
        "1 Genesect SFA 40",
        "<br />",
        "<strong>Trainer: 28</strong>",
        "4 Lillie's Determination MEG 119",
        "4 Tarragon POR 85",
        "3 Gwynn PBL 78",
        "3 Boss's Orders ASC 183",
        "4 Fighting Gong MEG 116",
        "4 Poké Pad ASC 198",
        "1 Special Red Card CRI ",
        "2 Air Balloon ASC 181",
        "3 Battle Cage PFL 85",
        "<br />",
        "<strong>Energy: 13</strong>",
        "8 Fighting Energy MEE 6",
        "4 Prism Energy BLK 86",
        "1 Legacy Energy TWM 167"],
    "./decklistImages/okidogi.png",
    "http://my.limitlesstcg.com/shared/6a4f22d29170a933a6a4cb79"
);

// Mega Darkrai burn deck
var megaDarkrai = new DeckList("Mega Darkrai ex burn",
    ["<strong>Pokémon: 12</strong>",
        "3 Mega Kangaskhan ex MEG 104",
        "2 Mega Darkrai ex PBL 48",
        "2 Latias ex SSP 76",
        "2 Pecharunt ex SFA 39",
        "1 Volcanion ex JTG 31",
        "1 Fezandipiti ex ASC 142",
        "1 Meowth ex POR 62",
        "<br />",
        "<strong>Trainer: 38</strong>",
        "4 Lillie's Determination ASC 192",
        "4 Team Rocket's Petrel ASC 207",
        "4 Janine's Secret Art PRE 112",
        "4 Cyrano SSP 170",
        "3 Boss's Orders MEG 114",
        "4 Dark Bell PBL 75",
        "4 Pokégear 3.0 BLK 84",
        "3 Ultra Ball ASC 213",
        "1 Switch MEG 130",
        "1 Special Red Card CRI 82",
        "1 Prime Catcher PRE 119",
        "1 Mega Signal ASC 193",
        "2 Lucky Helmet TWM 158",
        "2 Team Rocket's Factory ASC 203",
        "<br />",
        "<strong>Energy: 10</strong>",
        "10 Darkness Energy MEE 7"],
    "./decklistImages/megaDarkrai.png",
    "http://my.limitlesstcg.com/shared/6a65414b08e61199a0a4a739"
);
